"use client";

import Head from "next/head";
import "./globals.css";
import { Inter } from "next/font/google";

// wallet dependencies
import {
  EthereumClient,
  w3mConnectors,
  w3mProvider,
} from "@web3modal/ethereum";
import { Web3Modal } from "@web3modal/react";
import { configureChains, createConfig, WagmiConfig } from "wagmi";
import { arbitrum, mainnet, polygon, localhost, Chain } from "wagmi/chains";

const localnet: Chain = {
  id: 31337,
  name: "Localnet",
  nativeCurrency: {
    name: "Localnet Ethereum",
    symbol: "TestETH",
    decimals: 18,
  },
  rpcUrls: {
    default: {
      http: ["http://127.0.0.1:8545/"],
    },
    public: {
      http: ["http://127.0.0.1:8545/"],
    },
  },
  network: "localhost",
};

// wallet configuration
const chains = [arbitrum, mainnet, polygon, localhost, localnet];
const projectId = "78628cff4fa32f8236bacc8bdec91e4a";

const { publicClient } = configureChains(chains, [w3mProvider({ projectId })]);
const wagmiConfig = createConfig({
  autoConnect: true,
  connectors: w3mConnectors({ projectId, chains }),
  publicClient,
});
const ethereumClient = new EthereumClient(wagmiConfig, chains);

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <WagmiConfig config={wagmiConfig}>{children}</WagmiConfig>
          {/* web3 modal dialog box */}
          <Web3Modal projectId={projectId} ethereumClient={ethereumClient} />
        </main>
      </body>
    </html>
  );
}
